Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: aws-toolkit-ts-output/services/node_lambda/hello.handler
      CodeUri: /Users/tula/Programming/AwsMaster/ServerlessCdk
      Runtime: nodejs16.x
      Architectures:
        - x86_64
