Resources:
  SpaceApi1B373D2B:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: SpaceApi
    Metadata:
      aws:cdk:path: Space-finder/SpaceApi/Resource
  SpaceApiCloudWatchRole2811DDE0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: Space-finder/SpaceApi/CloudWatchRole/Resource
  SpaceApiAccount1ADAEF20:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - SpaceApiCloudWatchRole2811DDE0
          - Arn
    DependsOn:
      - SpaceApi1B373D2B
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: Space-finder/SpaceApi/Account
  SpaceApiDeploymentA2B9E7651dfaeaceb910e0edf8cef0991eccf965:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: SpaceApi1B373D2B
      Description: Automatically created by the RestApi construct
    DependsOn:
      - SpaceApihelloGET65983C27
      - SpaceApihelloDF776653
    Metadata:
      aws:cdk:path: Space-finder/SpaceApi/Deployment/Resource
  SpaceApiDeploymentStageprodBB8A31FE:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: SpaceApi1B373D2B
      DeploymentId:
        Ref: SpaceApiDeploymentA2B9E7651dfaeaceb910e0edf8cef0991eccf965
      StageName: prod
    DependsOn:
      - SpaceApiAccount1ADAEF20
    Metadata:
      aws:cdk:path: Space-finder/SpaceApi/DeploymentStage.prod/Resource
  SpaceApihelloDF776653:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - SpaceApi1B373D2B
          - RootResourceId
      PathPart: hello
      RestApiId:
        Ref: SpaceApi1B373D2B
    Metadata:
      aws:cdk:path: Space-finder/SpaceApi/Default/hello/Resource
  SpaceApihelloGETApiPermissionSpacefinderSpaceApi0274A94DGEThelloF2551934:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - thisIsNodejsLambdatFunctionID6D185135
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: SpaceApi1B373D2B
            - /
            - Ref: SpaceApiDeploymentStageprodBB8A31FE
            - /GET/hello
    Metadata:
      aws:cdk:path: Space-finder/SpaceApi/Default/hello/GET/ApiPermission.SpacefinderSpaceApi0274A94D.GET..hello
  SpaceApihelloGETApiPermissionTestSpacefinderSpaceApi0274A94DGEThelloEC2F16E7:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - thisIsNodejsLambdatFunctionID6D185135
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: SpaceApi1B373D2B
            - /test-invoke-stage/GET/hello
    Metadata:
      aws:cdk:path: Space-finder/SpaceApi/Default/hello/GET/ApiPermission.Test.SpacefinderSpaceApi0274A94D.GET..hello
  SpaceApihelloGET65983C27:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: SpaceApihelloDF776653
      RestApiId:
        Ref: SpaceApi1B373D2B
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - thisIsNodejsLambdatFunctionID6D185135
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: Space-finder/SpaceApi/Default/hello/GET/Resource
  thisIsSpaceTableName49DDE100:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: thisIsSpaceTableID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: thisIsSpaceTableID
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: thisIsSpaceTableName
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: Space-finder/thisIsSpaceTableName/Resource
  thisIsNodejsLambdatFunctionIDServiceRole0197CA1C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: Space-finder/thisIsNodejsLambdatFunctionID/ServiceRole/Resource
  thisIsNodejsLambdatFunctionIDServiceRoleDefaultPolicyE5B6DFEF:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:ListAllMyBuckets
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: thisIsNodejsLambdatFunctionIDServiceRoleDefaultPolicyE5B6DFEF
      Roles:
        - Ref: thisIsNodejsLambdatFunctionIDServiceRole0197CA1C
    Metadata:
      aws:cdk:path: Space-finder/thisIsNodejsLambdatFunctionID/ServiceRole/DefaultPolicy/Resource
  thisIsNodejsLambdatFunctionID6D185135:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: e8390b2866da477137b80bd7e36813bf283593f6898356c4630ba0a6e6ded4a1.zip
      Role:
        Fn::GetAtt:
          - thisIsNodejsLambdatFunctionIDServiceRole0197CA1C
          - Arn
      Environment:
        Variables:
          AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
      Handler: index.handler
      Runtime: nodejs14.x
    DependsOn:
      - thisIsNodejsLambdatFunctionIDServiceRoleDefaultPolicyE5B6DFEF
      - thisIsNodejsLambdatFunctionIDServiceRole0197CA1C
    Metadata:
      aws:cdk:path: Space-finder/thisIsNodejsLambdatFunctionID/Resource
      aws:asset:path: /home/magaz1nes/Programming/AwsMaster/ServerlessCdk/cdk.out/asset.e8390b2866da477137b80bd7e36813bf283593f6898356c4630ba0a6e6ded4a1
      aws:asset:is-bundled: true
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/1WRT0/DMAzFPwv3NFCGuHdD3Pijwb1yk1DcNklVJ0xV1e+O0zBtnPx7T7aTl9zLh1Le3cCJCqX7YsBGLh8BVC/YqhcYsYVgTjDL5WgoVCOKw5e7wkopH10QT2Yc/GwNI7tXire1JnkZeNTHSZk90EX87cz8YsK318nKtAoEy8f7Ifel+u4HVHOSmVYxgG00yCVZZrJIhN6lhufoVGBehZ4dWK854Sc0edkG5+HaeW06kq9bOc8J2tVAZALJKhXWch9Vb0KKsKYtbzGMMVzSbH0pLrr2XzTmg3ca833ScbKj25/yUZY7/oWOEIuJXxOtkcdcfwGF4d9poQEAAA==
    Metadata:
      aws:cdk:path: Space-finder/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  SpaceApiEndpointDA7E4050:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: SpaceApi1B373D2B
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: SpaceApiDeploymentStageprodBB8A31FE
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

